# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0001_initial'),
        ('backent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backent_api.Location'),
        ),
    ]
