# Generated by Django 2.0.2 on 2018-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent', '0002_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
