# Generated by Django 2.1.3 on 2019-01-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent', '0003_alter_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
