# Generated by Django 2.0.2 on 2018-02-19 22:13

from django.db import migrations

from backent.api import models


def duration2format(delta):
    if delta.days < 1:
        return models.EVENT_FORMAT_HOURS
    elif delta.days == 1:
        return models.EVENT_FORMAT_SHORT
    elif delta.days < 3:
        return models.EVENT_FORMAT_MEDIUM
    else:
        return models.EVENT_FORMAT_LONG


def transform_formats(apps, schema_editor):
    Event = apps.get_model('backent_api', 'Event')
    for event in Event.objects.all():
        event.event_format = duration2format(event.end - event.start)
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0003_add_npc_price_and_urls_and_move_currency'),
    ]

    operations = [
        migrations.RunPython(transform_formats),
    ]
