# Generated by Django 2.0.2 on 2018-02-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0004_migrate_event_formats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
    ]
