# Generated by Django 2.0.5 on 2018-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0006_make_events_unique_on_name_and_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('CHF', 'Swiss Francs (CHF)'), ('EUR', 'Euros (€)'), ('GBP', 'British pound (£)'), ('SEK', 'Swedish Krona (kr)'), ('USD', 'US Dollars ($)')], default='EUR', max_length=32),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=512),
        ),
    ]
