# Generated by Django 2.1.3 on 2018-12-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0007_auto_20180520_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(blank=True, help_text="To be expressed in cents of the event's currency", null=True, verbose_name='price (player)'),
        ),
    ]
