# Generated by Django 2.1.3 on 2018-12-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0008_make_price_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('beginner_friendly', 'Beginner friendly'), ('international', 'International'), ('pwd_friendly', 'PWD friendly'), ('underage_friendly', 'Underage friendly')], max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='backent_api.EventTag', blank=True, null=True),
        ),
    ]
