# Generated by Django 2.1.3 on 2019-01-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0012_populate_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='languages_spoken',
            field=models.ManyToManyField(blank=True, related_name='events', to='backent_api.Language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='backent_api.EventTag'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[('af', 'Afrikanns'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('bn', 'Bengali'), ('bo', 'Tibetan'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fj', 'Fiji'), ('fr', 'French'), ('ga', 'Irish'), ('gu', 'Gujarati'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croation'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('id', 'Indonesian'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('ka', 'Georgian'), ('km', 'Cambodian'), ('ko', 'Korean'), ('la', 'Latin'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mi', 'Maori'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('qu', 'Quechua'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sm', 'Samoan'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sv', 'Swedish '), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('to', 'Tonga'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('uk', 'Ukranian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('xh', 'Xhosa'), ('zh', 'Chinese (Mandarin')], max_length=32),
        ),
    ]
