# Generated by Django 2.1.3 on 2019-01-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0013_change_enums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='npc_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="To be expressed in the event's currency", max_digits=10, null=True, verbose_name='price (NPC)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="To be expressed in the event's currency", max_digits=10, null=True, verbose_name='price (player)'),
        ),
    ]
