# Generated by Django 2.1.3 on 2019-01-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0018_make_created_updated_at_auto_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('CAD', 'Canadian Dollars ($)'), ('CHF', 'Swiss Francs (CHF)'), ('DKK', 'Danish Krone (kr)'), ('EUR', 'Euros (€)'), ('GBP', 'British pound (£)'), ('NOK', 'Norwegian Krone (kr)'), ('RUB', 'Russian ruble (₽)'), ('SEK', 'Swedish Krona (kr)'), ('USD', 'US Dollars ($)')], default='EUR', max_length=32),
        ),
    ]
