# Generated by Django 2.1.3 on 2019-01-11 22:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent_api', '0019_add_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, help_text='Leave blank if the location is still inaccurate', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
